INSERT INTO produto (nome, descricao, preco, sku) VALUES
                                                      ('Apple iPhone 13', 'Smartphone da Apple com 128GB, câmera dupla e design elegante.', 7999.00, 'SKU001'),
                                                      ('Samsung Galaxy S21', 'Smartphone Samsung com display Dynamic AMOLED e performance robusta.', 6999.00, 'SKU002'),
                                                      ('Xiaomi Redmi Note 10', 'Smartphone Xiaomi com 64GB, câmeras versáteis e bateria duradoura.', 1999.00, 'SKU003'),
                                                      ('Motorola Moto G Power', 'Smartphone Motorola com bateria de longa duração e boa performance para o dia a dia.', 1499.00, 'SKU004'),
                                                      ('OnePlus 9', 'Smartphone OnePlus com design moderno, câmeras de alta resolução e carregamento rápido.', 6499.00, 'SKU005'),
                                                      ('Google Pixel 6', 'Smartphone Google com câmera avançada e integração total com serviços Google.', 5999.00, 'SKU006'),
                                                      ('Apple iPad Pro', 'Tablet Apple com tela Liquid Retina, desempenho elevado e suporte ao Apple Pencil.', 9999.00, 'SKU007'),
                                                      ('Samsung Galaxy Tab S7', 'Tablet Samsung com display de alta definição e experiência multimídia imersiva.', 4499.00, 'SKU008'),
                                                      ('Microsoft Surface Pro 7', 'Tablet 2-em-1 da Microsoft com performance robusta e versatilidade para trabalho e lazer.', 5499.00, 'SKU009'),
                                                      ('Amazon Fire HD 10', 'Tablet da Amazon com ótimo custo-benefício e performance adequada para entretenimento.', 1299.00, 'SKU010'),
                                                      ('Dell XPS 13', 'Laptop Dell com design compacto, desempenho elevado e tela InfinityEdge.', 8999.00, 'SKU011'),
                                                      ('Apple MacBook Air', 'Laptop Apple com performance eficiente, design leve e bateria de longa duração.', 8499.00, 'SKU012'),
                                                      ('HP Spectre x360', 'Laptop HP conversível com design premium, performance potente e tela sensível ao toque.', 7999.00, 'SKU013'),
                                                      ('Lenovo ThinkPad X1 Carbon', 'Laptop Lenovo com alta durabilidade, teclado confortável e desempenho profissional.', 9999.00, 'SKU014'),
                                                      ('Asus ZenBook 14', 'Laptop Asus com design ultrafino, boa performance e excelente autonomia.', 6499.00, 'SKU015'),
                                                      ('Apple iMac 27"', 'Desktop Apple com tela Retina 5K, design elegante e desempenho para profissionais criativos.', 12999.00, 'SKU016'),
                                                      ('Dell Inspiron Desktop', 'Desktop Dell com performance confiável para uso doméstico e profissional.', 3999.00, 'SKU017'),
                                                      ('HP Pavilion Gaming', 'Desktop HP com configuração voltada para jogos e performance robusta.', 5499.00, 'SKU018'),
                                                      ('Lenovo IdeaCentre 5', 'Desktop Lenovo com design moderno e performance equilibrada para tarefas diárias.', 3499.00, 'SKU019'),
                                                      ('Acer Aspire TC', 'Desktop Acer com bom custo-benefício e performance adequada para trabalho e estudo.', 2999.00, 'SKU020'),
                                                      ('Samsung QLED 4K TV', 'Televisor Samsung com tecnologia QLED, alta resolução e cores vibrantes.', 4999.00, 'SKU021'),
                                                      ('LG OLED55', 'Televisor LG com tecnologia OLED, oferecendo contraste perfeito e design sofisticado.', 5999.00, 'SKU022'),
                                                      ('Sony Bravia 65"', 'Televisor Sony com 65 polegadas, qualidade de imagem superior e recursos inteligentes.', 6999.00, 'SKU023'),
                                                      ('Philips 50" Ambilight TV', 'Televisor Philips com tecnologia Ambilight, proporcionando uma experiência imersiva.', 4299.00, 'SKU024'),
                                                      ('TCL 55" Roku TV', 'Televisor TCL com sistema Roku integrado, facilidade de uso e ótima relação custo-benefício.', 3899.00, 'SKU025'),
                                                      ('Bose QuietComfort 35 II', 'Fones de ouvido Bose com cancelamento de ruído e som de alta fidelidade.', 1999.00, 'SKU026'),
                                                      ('Sony WH-1000XM4', 'Fones de ouvido Sony com cancelamento ativo de ruído e conforto superior.', 2499.00, 'SKU027'),
                                                      ('JBL Flip 5', 'Caixa de som portátil JBL com som potente, resistente à água e bateria duradoura.', 899.00, 'SKU028'),
                                                      ('Anker Soundcore Flare', 'Caixa de som Anker com som 360°, luzes LED integradas e design moderno.', 699.00, 'SKU029'),
                                                      ('Sennheiser HD 660 S', 'Fones de ouvido Sennheiser com som de alta qualidade e conforto para longas sessões.', 1799.00, 'SKU030'),
                                                      ('Canon EOS Rebel T7', 'Câmera DSLR Canon com sensor de alta resolução e facilidade de uso para iniciantes.', 3499.00, 'SKU031'),
                                                      ('Nikon D3500', 'Câmera DSLR Nikon ideal para iniciantes com interface amigável e alta qualidade de imagem.', 3199.00, 'SKU032'),
                                                      ('Sony Alpha a6000', 'Câmera mirrorless Sony com autofoco rápido e design compacto.', 3899.00, 'SKU033'),
                                                      ('Fujifilm X-T30', 'Câmera mirrorless Fujifilm com alta resolução e excelente reprodução de cores.', 4599.00, 'SKU034'),
                                                      ('Panasonic Lumix GH5', 'Câmera mirrorless Panasonic com recursos avançados para vídeo e fotografia profissional.', 6499.00, 'SKU035'),
                                                      ('Apple Watch Series 6', 'Smartwatch da Apple com monitoramento de saúde avançado e design elegante.', 3599.00, 'SKU036'),
                                                      ('Samsung Galaxy Watch 4', 'Smartwatch Samsung com recursos fitness, integração Android e design moderno.', 2299.00, 'SKU037'),
                                                      ('Garmin Forerunner 245', 'Smartwatch Garmin focado em performance esportiva e monitoramento de atividades.', 1999.00, 'SKU038'),
                                                      ('Fitbit Versa 3', 'Smartwatch Fitbit com recursos de saúde e bem-estar, além de monitoramento contínuo.', 1599.00, 'SKU039'),
                                                      ('Huawei Watch GT 2', 'Smartwatch Huawei com longa duração de bateria e funcionalidades fitness.', 1499.00, 'SKU040'),
                                                      ('LG Refrigerator Inverter', 'Refrigerador LG com tecnologia inverter para maior eficiência energética.', 3999.00, 'SKU041'),
                                                      ('Samsung Family Hub Refrigerator', 'Refrigerador Samsung com tela interativa e recursos inteligentes para sua cozinha.', 6999.00, 'SKU042'),
                                                      ('Electrolux Frost Free Refrigerator', 'Refrigerador Electrolux com sistema frost free e design moderno.', 4499.00, 'SKU043'),
                                                      ('Brastemp Side by Side Refrigerator', 'Refrigerador Brastemp com layout side by side, oferecendo amplo espaço interno.', 5499.00, 'SKU044'),
                                                      ('Consul Frost Free Refrigerator', 'Refrigerador Consul com tecnologia frost free e economia de energia.', 3299.00, 'SKU045'),
                                                      ('Panasonic Inverter Microwave', 'Micro-ondas Panasonic com tecnologia inverter para cozimento uniforme.', 899.00, 'SKU046'),
                                                      ('LG Smart Inverter Microwave', 'Micro-ondas LG com funções inteligentes e tecnologia inverter.', 999.00, 'SKU047'),
                                                      ('Electrolux Countertop Microwave', 'Micro-ondas Electrolux compacto, ideal para cozinhas com espaço reduzido.', 799.00, 'SKU048'),
                                                      ('Samsung Microwave Oven', 'Micro-ondas Samsung com design moderno e diversas funções de preparo.', 849.00, 'SKU049'),
                                                      ('Whirlpool Microwave Oven', 'Micro-ondas Whirlpool com performance consistente e fácil operação.', 899.00, 'SKU050'),
                                                      ('LG Front Load Washer', 'Máquina de lavar LG com tecnologia de carregamento frontal e alta eficiência.', 2999.00, 'SKU051'),
                                                      ('Samsung Top Load Washer', 'Máquina de lavar Samsung com design prático e ótimo desempenho em lavagem.', 2499.00, 'SKU052'),
                                                      ('Electrolux Front Load Washer', 'Máquina de lavar Electrolux com sistema front load para melhor cuidado com as roupas.', 2799.00, 'SKU053'),
                                                      ('Brastemp 11kg Washer', 'Máquina de lavar Brastemp com capacidade de 11kg, ideal para famílias grandes.', 3199.00, 'SKU054'),
                                                      ('Bosch Series 6 Washer', 'Máquina de lavar Bosch com tecnologia avançada e alta eficiência energética.', 3599.00, 'SKU055'),
                                                      ('HP LaserJet Pro', 'Impressora HP LaserJet Pro com alta velocidade e qualidade de impressão.', 1299.00, 'SKU056'),
                                                      ('Canon Pixma TS9120', 'Impressora Canon Pixma com múltiplas funções e impressão de alta resolução.', 1399.00, 'SKU057'),
                                                      ('Epson EcoTank ET-4760', 'Impressora Epson EcoTank com tanque de tinta de alta capacidade e baixo custo por página.', 1699.00, 'SKU058'),
                                                      ('Brother HL-L2350DW', 'Impressora Brother monocromática com impressão rápida e conectividade sem fio.', 1099.00, 'SKU059'),
                                                      ('Samsung Xpress M2020W', 'Impressora Samsung compacta, ideal para escritórios de pequeno porte.', 999.00, 'SKU060'),
                                                      ('TP-Link Archer AX50', 'Roteador TP-Link com tecnologia Wi-Fi 6 para conexão de alta velocidade.', 799.00, 'SKU061'),
                                                      ('Asus RT-AX88U', 'Roteador Asus com desempenho robusto e tecnologia Wi-Fi 6 avançada.', 1299.00, 'SKU062'),
                                                      ('Netgear Nighthawk AX12', 'Roteador Netgear com design inovador e conectividade Wi-Fi 6 para alta performance.', 1499.00, 'SKU063'),
                                                      ('Linksys Velop Mesh', 'Sistema de roteadores Linksys Mesh para cobertura de sinal em toda a casa.', 1199.00, 'SKU064'),
                                                      ('D-Link AC3200', 'Roteador D-Link com alta velocidade e desempenho confiável para múltiplos dispositivos.', 899.00, 'SKU065'),
                                                      ('Sony PlayStation 5', 'Console Sony de última geração com gráficos avançados e performance excepcional.', 4999.00, 'SKU066'),
                                                      ('Microsoft Xbox Series X', 'Console Microsoft Xbox com alta performance e gráficos em 4K.', 4499.00, 'SKU067'),
                                                      ('Nintendo Switch', 'Console Nintendo versátil para jogos em casa e em movimento.', 2999.00, 'SKU068'),
                                                      ('Sony PlayStation 4 Pro', 'Console Sony com performance melhorada e suporte a jogos em alta definição.', 3999.00, 'SKU069'),
                                                      ('Microsoft Xbox One S', 'Console Microsoft Xbox com design compacto e ótima experiência de jogo.', 2999.00, 'SKU070'),
                                                      ('Alienware m15 R4', 'Gaming laptop Alienware com alta performance e design arrojado para gamers.', 11999.00, 'SKU071'),
                                                      ('Asus ROG Zephyrus G14', 'Gaming laptop Asus com desempenho potente e portabilidade para jogos intensos.', 9999.00, 'SKU072'),
                                                      ('MSI GS66 Stealth', 'Gaming laptop MSI com design elegante e performance de alto nível para jogos.', 10999.00, 'SKU073'),
                                                      ('Acer Predator Helios 300', 'Gaming laptop Acer com excelente performance e resfriamento eficiente para jogos.', 8999.00, 'SKU074'),
                                                      ('Lenovo Legion 5', 'Gaming laptop Lenovo com ótima performance e custo-benefício para gamers.', 7999.00, 'SKU075'),
                                                      ('Fitbit Charge 4', 'Fitness tracker Fitbit com monitoramento de atividades e recursos de saúde.', 799.00, 'SKU076'),
                                                      ('Xiaomi Mi Band 6', 'Fitness tracker Xiaomi com tela colorida e monitoramento contínuo.', 499.00, 'SKU077'),
                                                      ('Garmin Vivosmart 4', 'Fitness tracker Garmin com design discreto e monitoramento preciso de atividades.', 699.00, 'SKU078'),
                                                      ('Huawei Band 6', 'Fitness tracker Huawei com bateria de longa duração e monitoramento de saúde.', 549.00, 'SKU079'),
                                                      ('Samsung Galaxy Fit2', 'Fitness tracker Samsung com design moderno e recursos avançados de monitoramento.', 649.00, 'SKU080'),
                                                      ('Sonos One', 'Smart speaker Sonos com som de alta qualidade e integração com assistentes virtuais.', 1799.00, 'SKU081'),
                                                      ('Google Nest Audio', 'Smart speaker Google com design elegante e som nítido para sua casa.', 1499.00, 'SKU082'),
                                                      ('Amazon Echo', 'Smart speaker Amazon com assistente virtual Alexa para facilitar seu dia a dia.', 1299.00, 'SKU083'),
                                                      ('JBL Charge 4', 'Caixa de som JBL com bateria de longa duração e som potente para festas.', 999.00, 'SKU084'),
                                                      ('Bose Home Speaker 500', 'Smart speaker Bose com design sofisticado e qualidade sonora excepcional.', 1999.00, 'SKU085'),
                                                      ('Amazon Kindle Paperwhite', 'E-reader Amazon Kindle com tela antirreflexo e alta autonomia de bateria.', 999.00, 'SKU086'),
                                                      ('Kobo Clara HD', 'E-reader Kobo com design leve, tela de alta resolução e interface intuitiva.', 899.00, 'SKU087'),
                                                      ('Barnes & Noble Nook GlowLight 3', 'E-reader Nook com iluminação ajustável e interface amigável.', 799.00, 'SKU088'),
                                                      ('PocketBook InkPad 3', 'E-reader PocketBook com tela grande e ótima experiência de leitura digital.', 699.00, 'SKU089'),
                                                      ('Onyx Boox Nova3', 'E-reader Onyx Boox com tecnologia avançada e suporte a múltiplos formatos.', 1099.00, 'SKU090'),
                                                      ('Philips Hue Starter Kit', 'Kit de iluminação Philips Hue com lâmpadas inteligentes e controle via app.', 1199.00, 'SKU091'),
                                                      ('Google Nest Thermostat', 'Termostato inteligente Google Nest para controle de temperatura eficiente.', 899.00, 'SKU092'),
                                                      ('Amazon Echo Show 8', 'Smart display Amazon Echo Show com tela de 8 polegadas e assistente Alexa integrado.', 1299.00, 'SKU093'),
                                                      ('Arlo Pro 3', 'Câmera de segurança Arlo Pro com alta resolução e visão noturna.', 1799.00, 'SKU094'),
                                                      ('Ring Video Doorbell 3', 'Campainha inteligente Ring com vídeo HD e integração com smartphone.', 999.00, 'SKU095'),
                                                      ('Oral-B Genius X', 'Escova de dentes elétrica Oral-B com tecnologia inteligente para limpeza eficaz.', 799.00, 'SKU096'),
                                                      ('Philips Sonicare DiamondClean', 'Escova de dentes elétrica Philips Sonicare com múltiplas funções e design sofisticado.', 999.00, 'SKU097'),
                                                      ('Braun Series 7', 'Aparador de barba Braun com tecnologia avançada e acabamento preciso.', 899.00, 'SKU098'),
                                                      ('Remington HC4250', 'Secador de cabelo Remington com tecnologia iônica para redução do frizz.', 499.00, 'SKU099'),
                                                      ('Dyson Supersonic', 'Secador de cabelo Dyson com design inovador e performance superior.', 2999.00, 'SKU100');
